=== CheesyBoatRide/usb2snes/docs/applications/schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1617467807.json", 
	"title": "Root", 
	"type": "array",
	"default": [],
	"items":{
		"$id": "#root/items", 
		"title": "Items", 
		"type": "object",
		"required": [
			"name",
			"author",
			"short-description",
			"description",
			"website",
			"screenshot",
			"icon",
			"online"
		],
		"properties": {
			"name": {
				"$id": "#root/items/name", 
				"title": "Name", 
				"type": "string",
				"default": "",
				"examples": [
					"SaveState2Snes"
				],
				"pattern": "^.*$"
			},
			"author": {
				"$id": "#root/items/author", 
				"title": "Author", 
				"type": "string",
				"default": "",
				"examples": [
					"Skarsnik"
				],
				"pattern": "^.*$"
			},
			"short-description": {
				"$id": "#root/items/short-description", 
				"title": "Short-description", 
				"type": "string",
				"default": "",
				"examples": [
					"A software to handle your savestates on Sd2snes/Fxpak (pro) and Snes Classic"
				],
				"pattern": "^.*$"
			},
			"description": {
				"$id": "#root/items/description", 
				"title": "Description", 
				"type": "string",
				"default": "",
				"examples": [
					"A software that use the Usb2Snes firmware to allow you to save, load and organize savestates for your SNES games. Also support the SNES Classic with a special mod for Hakchi2 CE"
				],
				"pattern": "^.*$"
			},
			"website": {
				"$id": "#root/items/website", 
				"title": "Website", 
				"type": "string",
				"default": "",
				"examples": [
					"https://skarsnik.github.io/Savestate2snes/"
				],
				"pattern": "^.*$"
			},
			"screenshot": {
				"$id": "#root/items/screenshot", 
				"title": "Screenshot", 
				"type": "string",
				"default": "",
				"examples": [
					"https://skarsnik.github.io/Savestate2snes/webimage/main.png"
				],
				"pattern": "^.*$"
			},
			"icon": {
				"$id": "#root/items/icon", 
				"title": "Icon", 
				"type": "string",
				"default": "",
				"examples": [
					"https://raw.githubusercontent.com/Skarsnik/Savestate2snes/master/Icon126x126.png"
				],
				"pattern": "^.*$"
			},
			"online": {
				"$id": "#root/items/online", 
				"title": "Online", 
				"type": "boolean",
				"examples": [
					false
				],
				"default": true
			},
			"github-release": {
				"$id": "#root/items/github-release", 
				"title": "Github-release", 
				"type": "boolean",
				"examples": [
					true
				],
				"default": true
			},
			"repository": {
				"$id": "#root/items/repository", 
				"title": "Repository", 
				"type": "string",
				"default": "",
				"examples": [
					"https://github.com/Skarsnik/Savestate2snes"
				],
				"pattern": "^.*$"
			}
		}
	}

}

=== CheesyBoatRide/usb2snes/docs/applications/_data/list-apps.json
[
    {
        "name" : "QFile2Snes",
        "author" : "Skarsnik",
        "short-description" : "A software to explore and interact with your sd2snes/fxpak pro files",
        "description" : "Provided with QUsb2Snes. A software to explore your sd2snes/fxpak pro files. It allows you to upload/download file to the sd card. Also support drag and drop from your operating system file explorer.",
        "website" : "https://github.com/Skarsnik/QUsb2snes/tree/master/QFile2Snes",
        "screenshot" : "",
        "icon" : "https://raw.githubusercontent.com/Skarsnik/QUsb2snes/master/QFile2Snes/icon50x50.png",
        "online" : false,
        "github-release" : false,
        "repository" : "https://github.com/Skarsnik/QUsb2snes/"
    },
    {
        "name" : "SaveState2Snes",
        "author" : "Skarsnik",
        "short-description" : "A software to handle your savestates on Sd2snes/Fxpak (pro) and Snes Classic",
        "description" : "A software that use the Usb2Snes firmware to allow you to save, load and organize savestates for your SNES games. Also support the SNES Classic with a special mod for Hakchi2 CE",
        "website" : "https://skarsnik.github.io/Savestate2snes/",
        "screenshot" : "https://skarsnik.github.io/Savestate2snes/webimage/main.png",
        "icon" : "https://raw.githubusercontent.com/Skarsnik/Savestate2snes/master/Icon126x126.png",
        "online" : false ,
        "github-release" : true,
        "repository" : "https://github.com/Skarsnik/Savestate2snes"
    },
    {
       "name"  : "Multitroid",
       "author" : "OsteHovel",
       "short-description" : "Play Super Metroid co-op with all your friends",
       "description" : "Play Super Metroid co-op across internet and share energy, ammo, equipment, map tiles and events (such as bosses and flags)",
       "website" :  "http://www.multitroid.com",
       "screenshot" :  "",
       "icon" : "url to icon",
       "online" :  true
    },
    {
        "name"  : "FUNtoon",
        "author" : "Taw",
        "short-description" : "FUNtoon for all you Super Metroid need",
        "description" : "A multipurpose tool to improve you Super Metroid streaming experience and more. Crafted for her pleasure.",
        "website" :  "https://funtoon.party/",
        "screenshot" :  "",
        "icon" : "https://funtoon.party/img/funtoon_icon.777cea1f.svg",
        "online" :  true
    },
    {
        "name" : "PopTracker",
        "author" : "black-sliver",
        "short-description" : "Scriptable auto map-tracker, compatible to existing packs",
        "description" : "Powerful open progress tracker is a project to offer a universal, scriptable randomizer tracking solution that it is open source, runs everywhere and supports auto-tracking",
        "website" : "https://github.com/black-sliver/PopTracker",
        "screenshot" : "https://raw.githubusercontent.com/black-sliver/PopTracker/screenshots/screenshot.png",
        "icon" : "",
        "online" : false ,
        "github-release" : true,
        "repository" : "https://github.com/black-sliver/PopTracker"
    },
    {
        "name" : "MemoryViewer",
        "author" : "Redguyyyy",
        "short-description" : "A software to see/write various memories of your SD2Snes.",
        "description" : "A software to see/write various memories of your SD2Snes.",
        "website" : "https://github.com/RedGuyyyy/sd2snes/releases",
        "screenshot" : "",
        "icon" : "https://github.com/Skarsnik/QUsb2snes/raw/master/ui/icons/legacy.png",
        "online" : false,
        "github-release" : false,
        "repository" : "https://github.com/RedGuyyyy/usb2snesw"
    },
    {
        "name" : "Fileviewer (legacy)",
        "author" : "Redguyyyy",
        "short-description" : "A software to explore and interact with your sd2snes/fxpak pro files",
        "description" : "This application allows you access your SD2SNES files and perform some special operation, like starting a game, applying a patch.",
        "website" : "https://github.com/RedGuyyyy/sd2snes/releases",
        "screenshot" : "",
        "icon" : "https://github.com/Skarsnik/QUsb2snes/raw/master/ui/icons/legacy.png",
        "online" : false,
        "github-release" : false,
        "repository" : "https://github.com/RedGuyyyy/usb2snesw"
    },
    {
        "name" : "InputViewer (legacy)",
        "author" : "Redguyyyy",
        "short-description" : "A software to display your controller input.",
        "description" : "It's a patched [NintendoSpy](https://github.com/jaburns/NintendoSpy) that use some memory value of your device to display the buttons your press. It has some limitations like not showing input during screen transition and such.",
        "website" : "https://github.com/RedGuyyyy/sd2snes/releases",
        "screenshot" : "",
        "icon" : "https://github.com/Skarsnik/QUsb2snes/raw/master/ui/icons/legacy.png",
        "online" : false,
        "github-release" : false,
        "repository" : "https://github.com/RedGuyyyy/usb2snesw"
    }
]

=== CheesyBoatRide/usb2snes/docs/applications/list-apps.json
[
    {
        "name" : "QFile2Snes",
        "author" : "Skarsnik",
        "short-description" : "A software to explore and interact with your sd2snes/fxpak pro files",
        "description" : "Provided with QUsb2Snes. A software to explore your sd2snes/fxpak pro files. It allows you to upload/download file to the sd card. Also support drag and drop from your operating system file explorer.",
        "website" : "https://github.com/Skarsnik/QUsb2snes/tree/master/QFile2Snes",
        "screenshot" : "",
        "icon" : "https://raw.githubusercontent.com/Skarsnik/QUsb2snes/master/QFile2Snes/icon50x50.png",
        "online" : false,
        "github-release" : false,
        "repository" : ""
    },
    {
        "name" : "SaveState2Snes",
        "author" : "Skarsnik",
        "short-description" : "A software to handle your savestates on Sd2snes/Fxpak (pro) and Snes Classic",
        "description" : "A software that use the Usb2Snes firmware to allow you to save, load and organize savestates for your SNES games. Also support the SNES Classic with a special mod for Hakchi2 CE",
        "website" : "https://skarsnik.github.io/Savestate2snes/",
        "screenshot" : "https://skarsnik.github.io/Savestate2snes/webimage/main.png",
        "icon" : "https://raw.githubusercontent.com/Skarsnik/Savestate2snes/master/Icon126x126.png",
        "online" : false ,
        "github-release" : true,
        "repository" : "https://github.com/Skarsnik/Savestate2snes"
    },
    {
       "name"  : "Multitroid",
       "author" : "OsteHovel",
       "short-description" : "A way to play Super Metroid with shared inventory/ammunition/heal point accross multiple players",
       "description" : "A way to play Super Metroid with shared inventory/ammunition/heal point accross multiple players",
       "website" :  "http://www.multitroid.com",
       "screenshot" :  "todo.png",
       "icon" : "url to icon",
       "online" :  true,
       "github-release" : false,
       "repository" : "none"
    },
    {
        "name" : "PopTracker",
        "author" : "black-sliver",
        "short-description" : "Scriptable auto map-tracker, compatible to existing packs",
        "description" : "Powerful open progress tracker is a project to offer a universal, scriptable randomizer tracking solution that it is open source, runs everywhere and supports auto-tracking",
        "website" : "https://github.com/black-sliver/PopTracker",
        "screenshot" : "https://raw.githubusercontent.com/black-sliver/PopTracker/screenshots/screenshot.png",
        "icon" : "",
        "online" : false ,
        "github-release" : true,
        "repository" : "https://github.com/black-sliver/PopTracker"
    }
  
]
